source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'


urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='user_create'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='user_change'),
    path('<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='password_change')
]

source/hello/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('v2/', include('api_v2.urls')),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

source/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email')


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'birth_date']

source/accounts/views.py
from django.shortcuts import redirect, reverse
from django.contrib.auth import login, get_user_model
from django.views.generic import CreateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm
from django.core.paginator import Paginator
from django.contrib.auth.views import PasswordChangeView

from accounts.models import Profile


class RegisterView(CreateView):
    model = get_user_model()
    form_class = MyUserCreationForm
    template_name = 'user_create.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_page = self.request.GET.get('next')
        if not next_page:
            next_page = self.request.POST.get('next')
        if not next_page:
            next_page = reverse('webapp:index')

        return next_page


class UserDetailView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_related_by = 5
    paginate_related_orphans = 0

    def get_context_data(self, **kwargs):
        articles = self.object.articles.order_by('-created_at')
        paginator = Paginator(articles, self.paginate_related_by, orphans=self.paginate_related_orphans)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        kwargs['page_obj'] = page
        kwargs['articles'] = page.object_list
        kwargs['is_paginated'] = page.has_other_pages()
        return super().get_context_data(**kwargs)


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user == self.get_object()

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_profile_form(self):
        profile, _ = Profile.objects.get_or_create(user=self.object)
        form_kwargs = {'instance': profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(UserPassesTestMixin, PasswordChangeView):
    template_name = 'user_password_change.html'

    def test_func(self):
        return self.request.user.pk == self.kwargs.get('pk')

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.request.user.pk})

source/accounts/templates/login.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}
{% block menu %}<a class="nav-link" aria-current="page"  href="{% url 'webapp:index' %}">На главную</a>{% endblock %}

{% block content %}

    <h1 style="text-align: center">Вход</h1>

    <form action="" method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-error">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="mb-3 ">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" class="form-control mx-auto" id="username" name="username" style="max-width: 300px">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" class="form-control mx-auto" id="password" name="password"  style="max-width: 300px">
        </div>
        <button type="submit" class="btn btn-primary">Войти</button>
    </form>
{% endblock %}

source/accounts/templates/user_change.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}
{% block menu %}<a class="nav-link" aria-current="page" href="{% url 'accounts:user_detail' user_obj.pk %}">Назад</a>{% endblock %}

{% block content %}
    <h1>Поменять личные данные</h1>

    <form action="{% url 'accounts:user_change' user_obj.pk %}" method="post" enctype="multipart/form-data">

        {% csrf_token %}

        {% include 'partial/form.html' with form=form fields_only=True %}

        {% include 'partial/form.html' with form=profile_form fields_only=True %}

        <br>

        <input type="submit" value="Submit">

    </form>

{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}
{% block menu %}<a class="nav-link" aria-current="page"  href="{% url 'webapp:index' %}">На главную</a>{% endblock %}

{% block content %}
<h1>Регистрация</h1>

    {% include 'partial/form.html' with value_submit='Зарегистрироваться'  form_method='post' %}

{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}{{ user_obj.get_full_name }}{% endblock %}
{% block menu %}

        {% if request.user.is_authenticated and request.user == user_obj %}
            <a class="nav-link" aria-current="page" href="{% url 'accounts:user_change' request.user.pk %}">Редактировать</a>
            <a class="nav-link" aria-current="page" href="{% url 'accounts:password_change' request.user.pk %}">Смена пароля</a>
        {% endif %}
{% endblock %}

{% block content %}
    <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>
    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ user_obj.profile.avatar.url }}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Имя пользователя: {{ user_obj.username }}</h5>
                    <p class="card-text">Имя: {{ user_obj.first_name }}</p>
                    <p class="card-text">Фамилия: {{ user_obj.last_name }}</p>
                    <p class="card-text">Дата рождения: {{ user_obj.profile.birth_date|date:'d.m.Y' }}</p>
                    <p class="card-text">Почта: {{ user_obj.email }}</p>
                </div>
            </div>
        </div>
    </div>
   
    {% include 'partial/article_list.html' %}
    
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}



{% block title %}Смена пароля{% endblock %}



{% block menu %}<a class="nav-link" aria-current="page" href="{% url 'accounts:user_detail' request.user.pk %}">Назад</a>{% endblock %}




{% block content %}

    <h1>Смена пароля</h1>

    {% include 'partial/form.html' with form_method="post" value_submit='Сохранить' %}

{% endblock %}