source/hello/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('v2/', include('api_v2.urls')),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from django.views.generic import RedirectView
from webapp.views import IndexView, ArticleCreateView, ArticleView, ArticleUpdateView, ArticleDeleteView, \
    CommentCreateView, CommentUpdateView, CommentDeleteView, toggle_like

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('articles/', RedirectView.as_view(pattern_name='webapp:index')),
    path('articles/add/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>/', ArticleView.as_view(), name='article_view'),
    path('article/<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update_view'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete_view'),
    path('article/<int:pk>/comment/add/', CommentCreateView.as_view(), name='comment_add'),
    path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment_update_view'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete_view'),
    path('api/toggle_like/<str:model_name>/<int:item_id>/', toggle_like, name='toggle_like'),
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MinLengthValidator
from django.urls import reverse


class AbstractModel(models.Model):
    created_at = models.DateTimeField(verbose_name='Время создания', auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')

    class Meta:
        abstract = True


class Article(AbstractModel):
    title = models.CharField(max_length=50, null=False, blank=False, validators=[MinLengthValidator(4), ],
                             verbose_name="Заголовок")
    content = models.TextField(max_length=3000, null=False, blank=False, verbose_name='Контент')
    author = models.ForeignKey(get_user_model(), default=1, related_name='articles', on_delete=models.CASCADE, verbose_name="Автор")
    tags = models.ManyToManyField('webapp.Tag', blank=True, related_name='articles', verbose_name='Теги')

    def __str__(self):
        return f'{self.id}. {self.title}'

    def get_absolute_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.pk})


class Comment(AbstractModel):
    article = models.ForeignKey('webapp.Article', related_name='comments', on_delete=models.CASCADE,
                                verbose_name='Статья')
    text = models.TextField(max_length=400, verbose_name='Комментарий')

    author = models.ForeignKey(get_user_model(), default=1, related_name='comments', on_delete=models.CASCADE, verbose_name="Автор")

    def __str__(self):
        return self.text[:20]


class Tag(AbstractModel):
    name = models.CharField(max_length=31, verbose_name='Тег')

    def __str__(self):
        return self.name


class Like(models.Model):
    user = models.ForeignKey(get_user_model(), related_name='likes', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class LikedItem(models.Model):
    likes = models.ManyToManyField(Like, related_name='liked_items', blank=True)

    def get_likes_count(self):
        return self.likes.count()


class ArticleLikedItem(LikedItem):
    article = models.OneToOneField('webapp.Article', related_name='liked_item', on_delete=models.CASCADE)


class CommentLikedItem(LikedItem):
    comment = models.OneToOneField('webapp.Comment', related_name='liked_item', on_delete=models.CASCADE)

source/webapp/forms.py
from django import forms
from webapp.models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content', 'tags', )
        widgets = {'tags': forms.CheckboxSelectMultiple}
        error_messages = {
            'title': {
                'required': 'Please enter',
                'min_length': 'Заголовок слишком короткий'
            }
        }

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        content = cleaned_data.get('content')
        if title == content:
            raise forms.ValidationError('Заголовок и Контент не могут быть одинаковые')
        return cleaned_data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Найти')

source/webapp/views/api_views.py
# from django.http import JsonResponse
# from django.shortcuts import get_object_or_404
# from django.views.decorators.http import require_GET
# from django.contrib.auth.decorators import login_required
# from webapp.models import Article, Comment, Like, ArticleLikedItem, CommentLikedItem
#
# @login_required
# @require_GET
# def toggle_like(request, model_name, item_id):
#     user = request.user
#     liked_item_model = {'article': Article, 'comment': Comment}[model_name.lower()]
#     liked_item = get_object_or_404(liked_item_model, id=item_id)
#
#     liked_item_liked_model = {'article': ArticleLikedItem, 'comment': CommentLikedItem}[model_name.lower()]
#     liked_item_liked, created = liked_item_liked_model.objects.get_or_create(**{model_name.lower(): liked_item})
#
#     if user in liked_item_liked.likes.all():
#         liked_item_liked.likes.remove(user)
#     else:
#         like = Like.objects.create(user=user)
#         liked_item_liked.likes.add(like)
#
#     likes_count = liked_item_liked.get_likes_count()
#     return JsonResponse({'likes_count': likes_count})


from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_GET
from django.contrib.auth.decorators import login_required
from webapp.models import Article, Comment, Like, ArticleLikedItem, CommentLikedItem

@login_required
@require_GET
def toggle_like(request, model_name, item_id):
    user = request.user
    liked_item_model = {'article': Article, 'comment': Comment}[model_name.lower()]
    liked_item = get_object_or_404(liked_item_model, id=item_id)

    liked_item_liked_model = {'article': ArticleLikedItem, 'comment': CommentLikedItem}[model_name.lower()]
    liked_item_liked, created = liked_item_liked_model.objects.get_or_create(**{model_name.lower(): liked_item})

    if user in liked_item_liked.likes.all():
        liked_item_liked.likes.remove(user)
    else:
        # Check if the user has already liked the item
        existing_like = Like.objects.filter(user=user, liked_items=liked_item_liked).first()

        if existing_like:
            # User already liked the item, so remove the like
            existing_like.delete()
        else:
            # User hasn't liked the item, so add the like
            like = Like.objects.create(user=user)
            liked_item_liked.likes.add(like)

    likes_count = liked_item_liked.get_likes_count()
    return JsonResponse({'likes_count': likes_count})

source/webapp/views/article_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode

from django.db.models import Q
from webapp.models import Article
from webapp.forms import ArticleForm, SimpleSearchForm
from django.views.generic import View, FormView, ListView, DetailView, CreateView, UpdateView, DeleteView


class IndexView(ListView):
    model = Article
    template_name = 'articles/index.html'
    context_object_name = 'articles'
    paginate_by = 6
    paginate_orphans = 3
    ordering = ('-created_at',)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.search_form.is_valid():
            return self.search_form.cleaned_data['search']
        return None

    def dispatch(self, request, *args, **kwargs):
        print(request.user)
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(title__icontains=self.search_value) |
                                       Q(content__icontains=self.search_value))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.search_form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search_value'] = self.search_value
        return context


class ArticleView(DetailView):
    model = Article
    template_name = 'articles/article_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.order_by('-created_at')
        return context


class ArticleCreateView(LoginRequiredMixin, CreateView):
    template_name = 'articles/article_create.html'
    model = Article
    # fields = ['title', 'content', 'author', 'tags']
    form_class = ArticleForm

    def form_valid(self, form):
        self.article = form.save(commit=False)
        self.article.author = self.request.user
        self.article.save()
        form.save_m2m()
        return redirect('webapp:article_view', pk=self.article.pk)

    # def get_success_url(self):
    #     return reverse('webapp:article_view', kwargs={'pk': self.object.pk})


class ArticleUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'articles/article_update.html'
    model = Article
    form_class = ArticleForm
    permission_required = 'webapp.change_article'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().author

    # def dispatch(self, request, *args, **kwargs):
    #     self.article = self.get_object()
    #     return super().dispatch(request, *args, **kwargs)

    # def get_object(self):
    #     return get_object_or_404(Article, pk=self.kwargs.get('pk'))

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs['instance'] = self.article
    #     return kwargs

    # def form_valid(self, form):
    #     form.save()
    #     return redirect('webapp:article_view', pk=self.article.pk)


class ArticleDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'articles/article_delete.html'
    model = Article
    success_url = reverse_lazy('webapp:index')

    def test_func(self):
        return self.request.user.has_perm('webapp.delete_article') or self.request.user == self.get_object().author
    # def get(self, request, *args, **kwargs):
    #     article = get_object_or_404(Article, pk=kwargs.get('pk'))
    #     return render(request, 'articles/article_delete.html', {'article': article})
    #
    # def post(self, request, *args, **kwargs):
    #     article = get_object_or_404(Article, pk=kwargs.get('pk'))
    #     article.delete()
    #     return redirect('webapp:index')

source/webapp/views/comment_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import CreateView, UpdateView, DeleteView
from webapp.models import Comment, Article
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect
from webapp.forms import CommentForm


class CommentCreateView(LoginRequiredMixin, CreateView):
    template_name = 'comments/comment_create.html'
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        article = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        comment = form.save(commit=False)
        comment.article = article
        comment.author = self.request.user
        comment.save()
        return redirect('webapp:article_view', pk=article.pk)


class CommentUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'comments/comment_update.html'
    model = Comment
    form_class = CommentForm
    permission_required = 'webapp.change_comment'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().author

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk})


class CommentDeleteView(PermissionRequiredMixin, DeleteView):
    model = Comment
    permission_required = 'webapp.delete_comment'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().author

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk})

source/webapp/templates/articles/article_create.html
{% extends 'base.html' %}

{% block title %}Create Article{% endblock %}
{% block menu %}<a class="nav-link" aria-current="page"  href="{% url 'webapp:index' %}">На главную</a>{% endblock %}

{% block content %}
<h1>Create Article</h1>
    
    {% include 'partial/form.html' with value_submit='Create' form_method='post'  %}

{% endblock %}

source/webapp/templates/articles/article_delete.html
{% extends 'base.html' %}

{% block title %}Delete Article{% endblock %}
{% block menu %}
    {% if request.user.is_authenticated %}
    <a class="nav-link" aria-current="page"  href="{% url 'webapp:index' %}">На главную</a>
    {% endif %}
{% endblock %}

{% block content %}
<h1>Delete Article</h1>

    <h3>Вы уверены, что хотите удалить статью "{{ article.title }}"?</h3>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="ДА"/>
</form>
    <a href="{% url 'webapp:article_view' pk=article.pk %}">Нет</a>

{% endblock %}

source/webapp/templates/articles/article_update.html
{% extends 'base.html' %}

{% block title %}Update Article{% endblock %}
{% block menu %}<a class="nav-link" aria-current="page"  href="{% url 'webapp:index' %}">На главную</a>{% endblock %}

{% block content %}
<h1>Update Article</h1>

    {% include 'partial/form.html' with value_submit='Update'  form_method='post'   %}

{% endblock %}

source/webapp/templates/articles/article_view.html
{% extends 'base.html' %}

{% block title %}{{ article.title }}{% endblock %}
{% block menu %}
    <a class="nav-link" aria-current="page" href="{% url 'webapp:index' %}">На главную</a>
    {% if perms.webapp.change_article or article.author == request.user %}
        <a class="nav-link" aria-current="page" href="{% url 'webapp:article_update_view' pk=article.pk %}">Редактировать</a>
    {% endif %}
    {% if perms.webapp.delete_article or article.author == request.user %}
        <a class="nav-link" aria-current="page" href="{% url 'webapp:article_delete_view' pk=article.pk %}">Удалить</a>
    {% endif %}

    {% if request.user.is_authenticated %}
        <a class="nav-link" aria-current="page" href="{% url 'webapp:comment_add' pk=article.pk %}">Добавить
            комментарий</a>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Article</h1>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ article.title }}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{ article.author }}</h6>
            <p class="card-text">{{ article.content }}</p>
            <p class="card-text">Tags: {% for tag in article.tags.all %}
                {{ tag.name }}{% if forloop.last %}.{% else %}, {% endif %}
            {% endfor %}
            </p>
            <p>{{ article.created_at }}</p>

            {% if request.user.is_authenticated %}
            <button class="like-button" data-model="article" data-item-id="{{ article.id }}" data-like-count-id="like-count-{{ article.id }}">Лайк</button>
            {% endif %}
            <span id="like-count-{{ article.id }}" class="like-count">{{ article.liked_item.get_likes_count }}</span>

        </div>
    </div>
    <h3 class="mt-2">Comments: </h3>
    <div class="row row-cols-3 mt-2">
        {% for comment in comments %}

            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Автор: {{ comment.author }}</h5>
                        <p class="card-text">{{ comment.text }}</p>
                        <p>{{ article.created_at }}</p>

                        {% if perms.webapp.change_comment or comment.author == request.user %}
                            <a href="{% url 'webapp:comment_update_view' pk=comment.pk %}"
                               class="card-link">Редактировать</a>
                        {% endif %}
                        {% if perms.webapp.delete_comment or comment.author == request.user %}
                            <a href="{% url 'webapp:comment_delete_view' pk=comment.pk %}" class="card-link">Удалить</a>
                        {% endif %}

                        {% if request.user.is_authenticated %}
                            <button class="like-button" data-model="comment" data-item-id="{{ comment.id }}" data-like-count-id="like-count-{{ comment.id }}">Лайк</button>
                        {% endif %}
                        <span id="like-count-{{ comment.id }}" class="like-count">{{ comment.liked_item.get_likes_count }}</span>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function() {
        $('.like-button').click(function() {
            var model = $(this).data('model');
            var itemId = $(this).data('item-id');
            var likeCountId = $(this).data('like-count-id');

            $.get(`/api/toggle_like/${model}/${itemId}/`, function(data) {
                $('#' + likeCountId).text(data.likes_count);
            });
        });
    });
</script>


{% endblock %}

source/webapp/templates/articles/index.html
{% extends 'base.html' %}

{% block menu %}
    {% if request.user.is_authenticated %}
    <a class="nav-link" aria-current="page" href="{% url 'webapp:article_create' %}">Создать статью</a>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Articles</h1>
    <div>
        {% include 'partial/simple_search.html' %}
    </div>
    {% include 'partial/article_list.html' %}
{% endblock %}